apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: register-app
spec:
  selector:
    app: register-app
  ports:
    - port: 8082       # External port exposed by the service
      targetPort: 8082 # Port on the pod/container
  type: NodePort        